spring.datasource.url=jdbc:postgresql://127.0.0.1:5433/property_manager
spring.datasource.username=property_manager_app
spring.datasource.password=${PROPERTY_MANAGER_DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
